### ISSUE TITLE
PageRank is incorrect

### ISSUE THREAD

**Issue by szarnyasg** [vasia/graphalytics-platforms-gelly#4]
PageRank does not take dangling nodes into account.

It seems the PageRank implementation is not complete as it does not take dangling vertices into account (https://github.com/GraphBLAS/LAGraph/issues/9):
![image](https://user-images.githubusercontent.com/1402801/63653803-f2c8f980-c771-11e9-8284-1aa46254193d.png)

A correct solution in terms of linear algebra (implemented in Julia) is as follows:

```julia
out = A*ones(N)
D = map(x -> x == 0 ? 1.0 : 0.0, out)
pr = ones(N)/N
for i in 1:iterations
    teleport = (1-d) / N
    importance = d * A'*(pr./out)
    dangling = d/N * sum(pr.*D)
    global pr = teleport .+ importance .+ dangling
end
```

The current PageRank results are definitely incorrect as they have negative values.

```console
java.lang.AssertionError: vertex 1 has correct value
Expected: is a numeric value within <1.0E-4> of <0.0>
     but: <-0.7257517637024848> differed by <0.7256517637024849>

	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at science.atlarge.graphalytics.validation.algorithms.pr.PageRankValidationTest.validatePageRank(PageRankValidationTest.java:115)
	at science.atlarge.graphalytics.validation.algorithms.pr.PageRankValidationTest.testDirectedPageRankOnValidationGraph(PageRankValidationTest.java:82)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by szarnyasg** [comment]
I took a stab at fixing this and made some progress, shown here:
https://github.com/vasia/graphalytics-platforms-gelly/compare/master...szarnyasg:pagerank-dangling?expand=1

I am currently using the directed LDBC Graphalytics `example-directed` graph for validation. Here, sinks are shown in dark grey and source vertices are shown in white, while the rest of the vertices are coloured to an in-between shade of grey.

![image](https://user-images.githubusercontent.com/1402801/64477977-0b89d400-d1a2-11e9-8c18-0b65e3403c51.png)

The first challenge was handling the "dangling vertices", i.e. sinks but I think I managed to take care of them using `ScatterGatherConfiguration`'s `setOptDegrees` (so that vertices know their outdegree) and the `DoubleSumAggregator` to sum their PageRank values.

My current issue is to reach the source vertices (2, 6, 7, and 9 in the example). The docs says that
> By default, the updates from the in-neighbors are used to modify the current vertex’s state and messages are sent to out-neighbors.

This rhymes well with PageRank's way of thinking but does not allow the uniform handling of source vertices and the rest of the vertices. Is there a way to get an update message to these vertices or should I take another route (e.g. using GAS instead of S-G) for the implementation?

Update: the PageRank examples [[1]](https://github.com/apache/flink/blob/master/flink-libraries/flink-gelly-examples/src/main/java/org/apache/flink/graph/examples/PageRank.java) [[2]](https://github.com/apache/flink/blob/master/flink-libraries/flink-gelly-examples/src/main/java/org/apache/flink/graph/examples/GSAPageRank.java) remark that _"The implementation assumes that each page has at least one incoming and one outgoing link"._ I also found this remark in [this commit](https://git-wip-us.apache.org/repos/asf?p=flink.git;a=blob;f=docs/libs/gelly_guide.md;h=29483852facf7b7a4aa733782d9cb3e0eac29e4d;hb=cc1a7979).

Update 2: I found that this problem can be worked around by sending an "empty message" (with 0.0 PageRank value) from the vertex to itself.
```java
sendMessageTo(vertex.getId(), 0.0);
```
Is there a reason against using this approach?
